### ISSUE TITLE
hyperf2.0版本无法安装此组件

### ISSUE THREAD

**Issue by SimonZhangCN** [lzy309/captcha#3]
组件中对hyperf的组件依赖为1.0版本的,  无法通过 composer require  安装,  希望升级能支持hyperf2.0的版本

**Comment by lzy309** [comment]
step1:composer require lizhaoyang/captcha:2.0
step2:执行php bin/hyperf.php vendor:publish hyperf/session
step3:config/autoload/middlewares.php添加 Hyperf\Session\Middleware\SessionMiddleware::class
